export enum Genre {
    "Beats",               
    "Chill/Lo Fi",         
    "Dance/EDM",           
    "Darkpsy/Hitech",      
    "Deep House",          
    "DnB/Neurofunk",       
    "Dubstep",             
    "Electronic/Downtempo",
    "Electro House",       
    "Future House",        
    "House",               
    "Orchestral",          
    "Hardcore/Rawstyle",   
    "Progressive Trance",  
    "Psytrance",           
    "Rap/Hip Hop",         
    "Reggae/Dancehall",    
    "Techno",              
    "Tech House",          
    "Trance",              
    "Trap",
    "Other"
}